site_name: EMBRACE - Documentation
nav:
    - Home: index.md
    - Getting Started: getting_started.md
    - Roadmap: roadmap.md
    - Architecture:
          - Overview: architecture/overview.md
    - Environment Variables: env_vars.md
    - Workflows:
          - Data Ingestion: workflows/data_ingestion.md
    - Databases:
          - SQLite: databases/sqlite.md
          - MySQL: databases/mysql.md

# for local use
use_directory_urls: false
