site_name: EMBRACE - Documentation
nav:
    - Home: index.md
    - Getting Started: getting_started.md
    - Architecture:
          - Overview: architecture/overview.md
          - Environment Variables: env_vars.md
          - Modules:
                - Overview: modules/index.md
                - Connectors: modules/connectors.md
                - Machine Learning (ML): modules/ml.md
          - Databases:
                - SQLite: databases/sqlite.md
                - MySQL: databases/mysql.md
    - Workflows:
          - Data Ingestion: workflows/data_ingestion.md
          - Cron Jobs: workflows/cron_jobs.md
    - Roadmap: roadmap.md

# for local use
use_directory_urls: false

# theme
theme:
    name: material
    palette:
        - scheme: default
          primary: indigo
          accent: indigo
          toggle:
              icon: material/weather-night
              name: Dark mode
        - scheme: slate
          primary: indigo
          accent: indigo
          toggle:
              icon: material/weather-sunny
              name: Light mode
    features:
        - content.code.copy
