services:
  db:
    image: embrace-mysql
    build:
      context: .
      dockerfile: Dockerfile
    container_name: embrace-mysql
    ports:
      - "3306:3306"
    env_file:
      - .env
    volumes:
    - mysql_data:/var/lib/mysql
    - ${IMDB_DATA_DIR}:/var/lib/mysql-files:ro
    - ./init_scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uroot -p$${MYSQL_ROOT_PASSWORD} || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    restart: unless-stopped

volumes:
  mysql_data: