name: Build MkDocs Site

permissions:
    contents: read
    deployments: write # required to create a deployment entry for cloudflare pages

on:
    push:
        branches:
            - main
        paths:
            - docs/**
    pull_request:
        paths:
            - docs/**
    workflow_dispatch:
        inputs:
            deploy:
                description: "Run deploy job (Cloudflare Pages)"
                required: false
                default: true
                type: boolean

jobs:
    build:
        # only allow pipeline to run on Github runner
        if: ${{ github.server_url == 'https://github.com' }}
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.11"

            - name: Install MkDocs + deps
              run: |
                  python -m pip install --upgrade pip
                  pip install mkdocs mkdocs-material mkdocs-material-extensions

            - name: Build documentation
              run: mkdocs build

            - name: Upload site artifact
              uses: actions/upload-artifact@v4
              with:
                  name: mkdocs-site
                  path: site
                  if-no-files-found: error

    deploy:
        needs: build
        if: >
            ${{
              (github.event_name == 'push' && github.ref == 'refs/heads/main')
              || (github.event_name == 'workflow_dispatch' && inputs.deploy == 'true')
            }}
        runs-on: ubuntu-latest
        steps:
            - name: Download built site
              uses: actions/download-artifact@v4
              with:
                  name: mkdocs-site
                  path: site

            - name: Publish to Cloudflare Pages
              uses: cloudflare/pages-action@v1
              with:
                  apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
                  accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
                  projectName: embrace-docs
                  directory: site
                  gitHubToken: ${{ secrets.GITHUB_TOKEN }}
